import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { useContext, useEffect } from 'react';
import { DummyContext } from '../context/DummyContext';
export { getServerSideProps } from '../server/pages';
import { useTranslation } from 'react-i18next';

export default function Home() {
  const router = useRouter();
  const dummy = useContext(DummyContext);
  const { t } = useTranslation(['common']);

  console.log(dummy.state);
  useEffect(() => {
    dummy.setState({
      a: 'foo'
    });
  }, []);

  function onClick() {
    router.push('/about');
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {t('hello', { defaultValue: 'I am default value'})}
        <button onClick={onClick}>go to about page</button>
      </main>
    </div>
  )
}
